"""Render the egress squid config and per-client allowlists (PLAN §2.2).

Output is a dict {file name: content}. The files go into one host dir that is
bind-mounted read-only at CONF_DIR in the egress container. `squid -k
reconfigure` in the container applies changes without a restart.
"""

from __future__ import annotations

import ipaddress
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .profile import NETWORK_MODES, hostname_problem, merge_domains

CONF_DIR = "/etc/squid/agentbox"
LOG_DIR = "/var/log/agentbox"
ACCESS_LOG = f"{LOG_DIR}/egress.log"
PORT = 3128
CLIENTS = ("agent", "router", "mcp-gateway")
HOST_NAMES = ("host.docker.internal", "gateway.docker.internal")

# Always denied destination ranges (checked on the resolved address).
# PLAN §2.2 list first, then extra non-public ranges.
PRIVATE_DST = (
    "0.0.0.0/8",
    "10.0.0.0/8",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
    "172.16.0.0/12",
    "192.168.0.0/16",
    # ::/96 = unspecified, loopback (::1), IPv4-compatible. Not ::1 on its own
    # (squid warns: subnetwork of ::/96). Never ::ffff:0:0/96: squid stores
    # IPv4 as v4-mapped, so that entry means all IPv4.
    "::/96",
    "100::/64",  # discard-only
    "2001::/32",  # Teredo
    "2001:db8::/32",  # documentation
    "64:ff9b:1::/48",  # local-use NAT64
    "fc00::/7",
    "fe80::/10",
    "fec0::/10",  # deprecated site-local
    "ff00::/8",
    "2002::/16",  # 6to4
    # extras: NAT64, IETF, benchmark, multicast, reserved.
    "64:ff9b::/96",
    "192.0.0.0/24",
    "198.18.0.0/15",
    "224.0.0.0/4",
    "240.0.0.0/4",
)

# IP-literal host names (`dstdom_regex -n -i`): dotted/integer/hex IPv4 forms
# (inet_aton style) and any host with a ':' (IPv6, bracketed or not). DNS
# names never contain ':' and never have an all-numeric last label
# (profile.hostname_problem), so these never match an allowed name.
IP_LITERAL_RES = (
    r"^(0x[0-9a-f]*|[0-9]+)(\.(0x[0-9a-f]*|[0-9]+)){0,3}\.?$",
    r"^\[?[0-9a-f.:%]*:[0-9a-f.:%a-z]*\]?$",
)


class EgressError(Exception):
    pass


@dataclass(frozen=True)
class Client:
    name: str
    ip: str
    domains: list[str]


def _check_domains(name: str, domains: list[str]) -> list[str]:
    for d in domains:
        if msg := hostname_problem(d):
            raise EgressError(f"{name} allowlist: {d!r}: {msg}")
    return merge_domains(domains)


def allow_file(client: str) -> str:
    return f"{client}.allow"


def render(
    mode: str,
    clients: list[Client],
    allow_http: bool = False,
    host_mcp_ports: list[int] | None = None,
) -> dict[str, str]:
    """Return {file name: content} for squid.conf and the allowlist files.

    `clients` must hold exactly agent, router, mcp-gateway (each with its fixed
    IP; domains may be empty). In `open` mode the agent list is ignored.
    """
    if mode not in NETWORK_MODES:
        raise EgressError(f"unknown network mode {mode!r}")
    by_name = {c.name: c for c in clients}
    if sorted(by_name) != sorted(CLIENTS) or len(clients) != len(CLIENTS):
        raise EgressError(f"clients must be exactly {CLIENTS}, got {[c.name for c in clients]}")
    ports = sorted(set(host_mcp_ports or ()))
    for p in ports:
        if not isinstance(p, int) or isinstance(p, bool) or not 1 <= p <= 65535:
            raise EgressError(f"invalid host MCP port {p!r}")
    ips = set()
    for c in clients:
        try:
            ipaddress.IPv4Address(c.ip)
        except ValueError:
            raise EgressError(f"{c.name}: invalid IPv4 address {c.ip!r}") from None
        ips.add(c.ip)
    if len(ips) != len(clients):
        raise EgressError("client IPs must be distinct")

    files: dict[str, str] = {}
    for c in clients:
        doms = _check_domains(c.name, c.domains)
        if c.name == "agent" and mode == "open":
            doms = []
        files[allow_file(c.name)] = "".join(d + "\n" for d in doms)

    connect_ports = "443 80" if allow_http else "443"
    L = [
        "# Generated by agentbox (PLAN §2.2). Do not edit: `agentbox allow` rewrites it.",
        f"http_port {PORT}",
        "pid_filename /run/squid/squid.pid",
        "cache deny all",
        "cache_mem 0 MB",
        f"access_log stdio:{ACCESS_LOG} squid",
        f"cache_log stdio:{LOG_DIR}/cache.log",
        "cache_store_log none",
        "logfile_rotate 0",
        "coredump_dir /tmp",
        "pinger_enable off",
        "via off",
        "forwarded_for delete",
        "httpd_suppress_version_string on",
        "shutdown_lifetime 1 seconds",
        "",
        "# clients (fixed IPs)",
    ]
    for c in clients:
        L.append(f"acl src_{c.name} src {c.ip}/32")
    L.append("")
    for c in clients:
        if c.name == "agent" and mode == "open":
            continue
        L.append(f'acl allow_{c.name} dstdomain -n "{CONF_DIR}/{allow_file(c.name)}"')
    L += [
        "acl ip_literal dstdom_regex -n -i " + " ".join(IP_LITERAL_RES),
        "acl private_dst dst " + " ".join(PRIVATE_DST),
        "acl host_dom dstdomain -n " + " ".join(HOST_NAMES),
        f"acl conn_ports port {connect_ports}",
        "acl CONNECT method CONNECT",
    ]
    if allow_http:
        L.append("acl plain_ports port 80")
    if ports:
        L.append("acl host_mcp_ports port " + " ".join(str(p) for p in ports))
    L += [
        "",
        "# always denied",
        "http_access deny manager",
        "http_access deny ip_literal",
    ]
    if ports:
        L += [
            "# gateway only: plain-HTTP forward requests to host MCP servers",
            "http_access allow src_mcp-gateway !CONNECT host_dom host_mcp_ports",
        ]
    L += [
        "http_access deny host_dom",
        "http_access deny private_dst",
        "http_access deny CONNECT !conn_ports",
        "http_access deny !CONNECT !plain_ports" if allow_http else "http_access deny !CONNECT",
        "",
        f"# per-client allowlists (agent mode: {mode})",
    ]
    for c in clients:
        if c.name == "agent" and mode == "open":
            L.append("http_access allow src_agent")
        else:
            L.append(f"http_access allow src_{c.name} allow_{c.name}")
    L += ["http_access deny all", ""]
    files["squid.conf"] = "\n".join(L)
    return files


def write(conf_dir: str | Path, files: dict[str, str]) -> None:
    """Write files atomically (rename in place) so squid never reads a partial file.

    Allowlists are written before squid.conf.
    """
    d = Path(conf_dir)
    d.mkdir(parents=True, exist_ok=True)
    for name in sorted(files, key=lambda n: n == "squid.conf"):
        fd, tmp = tempfile.mkstemp(dir=d, prefix=f".{name}.")
        with os.fdopen(fd, "w") as f:
            f.write(files[name])
        os.chmod(tmp, 0o644)
        os.replace(tmp, d / name)


# Run in the egress container after write(). Squid parses the new config first;
# on a parse error the -k process exits non-zero and the running squid keeps
# the old config (verified with squid 6.13).
RELOAD_ARGV = ["squid", "-k", "reconfigure", "-f", f"{CONF_DIR}/squid.conf"]
